### ISSUE TITLE
Recommendations 

### ISSUE THREAD

**Issue by keikeka** [Moyrasc/Todolist-Using-React#4]
Recommendations to improve the user interface, you could add in this class, the following properties: 
- user-select: none, to prevent the user from selecting the text. 
- cursor: pointer, to change the text selection icon to a clickable arrow. 

https://github.com/Moyrasc/Todolist-Using-React/blob/9c1260dd6fb35c80460be420f554a7c02c050847/src/styles/index.css#L11

**Comment by Moyrasc** [comment]
I have applied the code improvements :)
