### ISSUE TITLE
Check and correct the margins

### ISSUE THREAD

**Issue by keikeka** [Moyrasc/Todolist-Using-React#5]
Check the bootstrap classes with those of the css file, because you are clashing the margins and creating a horizontal scroll.

https://github.com/Moyrasc/Todolist-Using-React/blob/9c1260dd6fb35c80460be420f554a7c02c050847/src/js/component/home.jsx#L9

**Comment by Moyrasc** [comment]
I modified the margins and managed to eliminate the vertical scroll but with the horizontal one even applying a max-width:100vw it didn't work so for the moment I used the overflow-x: hidden so it doesn't appear.
